
  addr: "localhost:8080"
  db_path: "storage/database.db"
  timeout: 30s

  redis:
    addr: "localhost:6379"
    exp_time: 15m

  importer:
    enabled: false
    file: "math-source/test_source.jsonl"